POST http://localhost:3001/api/blogs
content-Type: application/json

{
    "title": "Rahoiksi gradulla?",
    "author": "Santeri Aikio",
    "url": "https://www.jyu.fi/fi/blogikirjoitus/rahoiksi-gradulla",
    "likes": 7
}
